### ISSUE TITLE
Lines with 2 points are broken as of 3.1.7

### ISSUE THREAD

**Issue by isaac-mason** [pmndrs/meshline#14]
Using MeshLineGeometry with 2 points is broken as of 3.1.7, nothing is rendered.

e.g.
```ts
const geometry = new MeshLineGeometry()
const points = [
  0, 0, 0,
  1, 1, 1
]
geometry.setPoints(points)
```

So far I've narrowed the issue down a change in this commit: https://github.com/pmndrs/meshline/commit/3244cda5c9dd781f667e7fef95b0cae7a2de9246

I can add a repro shortly, just figuring out what I can use other than codesandbox (they've added more limits for free users)

**Comment by GoreStarry** [comment]
I have the same issue. Now MeshLineGeometry need at least three points to draw.
