### ISSUE TITLE
Should latest release be v3.3.1?

### ISSUE THREAD

**Issue by Methuselah96** [pmndrs/meshline#20]
Not sure where v3.3.0 came from since it's not included in the repo, but v3.3.0 was the latest release version before the v3.2.1 from a few days ago according to npm:

![image](https://github.com/pmndrs/meshline/assets/693755/eee0665c-4e59-4328-ac1e-bef05ebf66c2)

Should the latest version be bumped to v3.3.1 to account for this?

**Comment by Methuselah96** [comment]
Looks like v3.3.0 contains https://github.com/pmndrs/meshline/pull/15, and the version number was just bumped in the repo.

**Comment by CodyJasonBennett** [comment]
Good catch. Fixed.
